# fly.toml app configuration file generated for olxparser on 2023-08-03T17:36:59+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "olxparser"
primary_region = "den"

[build]


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
